{{- if and .Values.route.enabled (not .Values.ingress.enabled) -}}
{{- $fullName := include "uptime-kuma.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
    {{- with .Values.route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.route.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    link.argocd.argoproj.io/external-link: "https://{{ .Values.route.host }}"
spec:
  host: {{ .Values.route.host | quote }}
  to:
    kind: Service
    name: {{ $fullName }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
