{{- if .Values.serviceMonitor.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-credentials
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
type: Opaque
data:
  username: <username>
  password: <token>
{{- end }}
