{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.authentication.enabled (not .Values.serviceMonitor.authentication.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-credentials
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.serviceMonitor.authentication.username | quote }}
  password: {{ .Values.serviceMonitor.authentication.password | quote }}
{{- end }}
