---
{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.authentication.enabled (not .Values.serviceMonitor.authentication.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-credentials
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
  annotations:
    description: "Credentials for Uptime Kuma service monitor"
type: Opaque
data:
  username: {{ .Values.serviceMonitor.authentication.username | quote }}
  password: {{ .Values.serviceMonitor.authentication.password | quote }}
{{- end }}

---
{{- if .Values.externalDatabase.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-env-credentials
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
  annotations:
    description: "Credentials for an external database"
type: Opaque
data:
  UPTIME_KUMA_DB_TYPE: {{ .Values.externalDatabase.type | b64enc }}
  UPTIME_KUMA_DB_PORT: {{ .Values.externalDatabase.port | toString | b64enc }}
  UPTIME_KUMA_DB_HOSTNAME: {{ .Values.externalDatabase.hostname | b64enc }}
  UPTIME_KUMA_DB_USERNAME: {{ .Values.externalDatabase.username | b64enc }}
  UPTIME_KUMA_DB_PASSWORD: {{ .Values.externalDatabase.password | b64enc }}
  UPTIME_KUMA_DB_NAME: {{ .Values.externalDatabase.dbName | b64enc }}
{{- end }}
